# Generated by Django 5.2.4 on 2025-08-03 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="published_year",
        ),
        migrations.AddField(
            model_name="book",
            name="published_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
